CREATE TABLE INCENTIVES(
EMPLOYEE_REF_ID   NUMBER ,
INCENTIVE_DATE    DATE,
INCENTIVE_AMOUNT  NUMBER,

FOREIGN KEY(EMPLOYEE_REF_ID)
REFERENCES EMPLOYEE(EMP_ID)
);

DROP TABLE INCENTIVES;
INSERT INTO INCENTIVES VALUES(
1,TO_DATE('01-FEB-13','DD-MM-YY'),5000);

INSERT INTO INCENTIVES VALUES(
2,TO_DATE('01-FEB-13','DD-MM-YY'),3000);

INSERT INTO INCENTIVES VALUES(
3,TO_DATE('01-FEB-13','DD-MM-YY'),4000);

INSERT INTO INCENTIVES VALUES(
1,TO_DATE('01-JAN-13','DD-MM-YY'),4500);

INSERT INTO INCENTIVES  VALUES(
2,TO_DATE('01-JAN-13','DD-MM-YY'),3500);

SELECT * FROM INCENTIVES;

SELECT * FROM EMPLOYEE WHERE EMP_ID = 3;
